name: Lint

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    lint:
        name: Lint TS and CSS
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

            - name: Setup node env
              uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci --no-audit

            - name: Build for production
              run: npm run build

            - name: Run ESLint
              run: npm run lint
